.vscode/settings.json, assets/css/style.css, index.html
Add Google Fonts and set header to 0 in css
Add collapsible navbar logo, Home, Game, About
=> GC issue13

README.md
Add README template with sections to fill-out during project.
=> Add README template structure

assets/css/style.css
- amended background-image url to ../images/ etc
=> amended background-image url to appear correctly once pushed to main

assets/js/item-array.js
**Description""
Added items to array for the following bins:
Recycling Bin
Organic Bin
General Waste Bin
Glass Bin
=> Update array items to item-array.js

assets/js/fact-object.js, assets/js/item-array.js
Added additional items to general waste array
Added additional facts to facts array
=> Add additional items to general waste and also facts

about.html
**footer**
start to work on footer
=> create a footer

index.html
- added missing end div to all divs with the class of row
=> BUG FIX: div with the class of row had missing end div

assets/css/style.css, index.html
Added Caring for the Planet text
Styled text for same
=> Gc issue60

assets/css/style.css, game.html
Bare bones of the game modal added. To be customised in conjunction with Damian.
=> Add modal to game.html

about.html, assets/css/style.css
** footer**
layout and style added to footer for about us page
=> add footer layout and style

about.html, assets/css/style.css, game.html, index.html
Logo taken out of toggle menu and animation added. Colour added to nav bar.
=> Tidy up navbar

game.html
Add footer to game page
Add Font Awesome script to  head
Add copyright script for current year to game page
=> Add footer, font awesome & copyright scripts to game page

assets/css/style.css, assets/js/item-array.js, assets/js/script.js, game.html
Finalized game logic, made some minor updates to game.html
=> Dj issue57

assets/css/style.css, index.html
-took the padding out of the home cards to improve look of card images in cards
-changed the home card styling to better match the about us card styling
=> Changed home page styling to better match the about page styling

about.html, assets/css/style.css
**About us page**
Shadow added  style added to let's do it section in about us page
=> add shadow to let do it together

assets/css/style.css, assets/js/script.js, game.html
Created some media queries for the game area
=> Make game responsive, update styling

index.html
**Button link**
Button link added to game page
=> button link added in the main page

assets/css/style.css, index.html
- Changed font of title from Roboto to Banger form home
- Changed the styling of title for home
=> Changed home title font and styling

game.html
Add tutorial information for game play.
Provide information on the bins available and their associated items.
=> Add Tutorial information for game.

assets/css/style.css, index.html
- Added underline to button text
- Altered btn and btn-primary class to better suit sites aesthetics
=> Amending btn and btn-primary classes to better suite aesthetics of site

about.html, assets/css/style.css
**About us**
More Style added to About Us page
=> add more style to about us page

about.html, assets/css/style.css
**Padding & Font size**
Padding added to About Us page.
Font size increased for Headers
=> Sh issue54

assets/css/style.css, game.html
Fix white gap at bottom of game page
=> Dj issue101

assets/css/style.css
=> Rebuild effort second attempt

about.html, game.html, index.html
=> Added alt to logo

about.html, game.html, index.html
Added alt text to images on all pages
=> Added alt text to images on all pages
